login: &login
  adapter: mysql
  username: root
  password: 
  host: localhost

development:
  <<: *login
  database: yoke_dev

test:
  <<: *login
  database: yoke_test

production:
  <<: *login
  database: yoke_prod
